import { ArrowLeft, Sparkles, AlertTriangle, CheckCircle, XCircle, FileText, Copy, TrendingUp, MapPin, Clock } from 'lucide-react';

export function ComplianceDetail({ onBack }: { onBack: () => void }) {
  return (
    <div className="flex-1 overflow-auto bg-gray-50 dark:bg-black">
      <div className="p-8 max-w-[1600px] mx-auto">
        {/* Header */}
        <div className="mb-6">
          <button 
            onClick={onBack}
            className="flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white mb-4 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-medium">Back to Compliance</span>
          </button>
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Transaction #TXN-2024-0482</h1>
                <span className="px-3 py-1 bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-400 text-sm font-semibold rounded-full">
                  High Risk
                </span>
              </div>
              <p className="text-gray-600 dark:text-gray-400">Flagged 2 hours ago • Awaiting review</p>
            </div>
            <div className="flex gap-3">
              <button className="px-4 py-2 bg-white dark:bg-gray-950 border border-gray-200 dark:border-gray-800 text-gray-700 dark:text-gray-300 font-medium rounded-lg hover:bg-gray-50 dark:hover:bg-gray-900 transition-colors flex items-center gap-2">
                <FileText className="w-4 h-4" />
                Request Docs
              </button>
              <button className="px-4 py-2 bg-red-600 text-white font-medium rounded-lg hover:bg-red-700 transition-colors flex items-center gap-2">
                <XCircle className="w-4 h-4" />
                Block
              </button>
              <button className="px-4 py-2 bg-emerald-600 text-white font-medium rounded-lg hover:bg-emerald-700 transition-colors flex items-center gap-2">
                <CheckCircle className="w-4 h-4" />
                Approve
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
          {/* Left Column */}
          <div className="xl:col-span-2 space-y-6">
            {/* AI Analysis - The "Wow" Feature */}
            <div className="bg-gradient-to-br from-blue-50 via-white to-indigo-50 dark:from-blue-950/20 dark:via-gray-950 dark:to-indigo-950/20 rounded-2xl p-8 border-2 border-blue-200 dark:border-blue-900">
              <div className="flex items-start gap-4 mb-6">
                <div className="w-14 h-14 bg-blue-600 rounded-2xl flex items-center justify-center flex-shrink-0">
                  <Sparkles className="w-7 h-7 text-white" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">AI Compliance Analysis</h2>
                  <p className="text-gray-600 dark:text-gray-400">Generated by PayOS Compliance Copilot • Updated 5 min ago</p>
                </div>
              </div>

              {/* Why Flagged */}
              <div className="mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <AlertTriangle className="w-5 h-5 text-red-600 dark:text-red-400" />
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Why This Was Flagged</h3>
                </div>
                <div className="space-y-3">
                  <div className="flex gap-3">
                    <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 dark:text-gray-300">
                      <strong>Unusual transaction pattern:</strong> This contractor typically receives $2,500-$3,000 monthly. This $15,000 payment is 5x the normal amount.
                    </p>
                  </div>
                  <div className="flex gap-3">
                    <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 dark:text-gray-300">
                      <strong>Geographic risk:</strong> First payment to a contractor in a high-risk jurisdiction (based on FATF guidance).
                    </p>
                  </div>
                  <div className="flex gap-3">
                    <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 dark:text-gray-300">
                      <strong>Velocity alert:</strong> Third transaction from this employer in the past 24 hours, totaling $42,000.
                    </p>
                  </div>
                  <div className="flex gap-3">
                    <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 dark:text-gray-300">
                      <strong>KYC timing:</strong> Contractor completed KYC only 3 days ago. Typically we see a longer lead time before large payments.
                    </p>
                  </div>
                </div>
              </div>

              {/* Risk Score */}
              <div className="mb-6 p-5 bg-white dark:bg-gray-950 rounded-xl border border-gray-200 dark:border-gray-800">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="font-semibold text-gray-900 dark:text-white">Risk Assessment</h4>
                  <span className="text-2xl font-bold text-red-600 dark:text-red-400">85%</span>
                </div>
                <div className="h-2 bg-gray-200 dark:bg-gray-800 rounded-full overflow-hidden mb-3">
                  <div className="h-full bg-gradient-to-r from-red-500 to-red-600 rounded-full" style={{ width: '85%' }}></div>
                </div>
                <p className="text-sm text-gray-700 dark:text-gray-300">
                  While the individual factors are explainable, the combination of velocity, amount anomaly, and timing creates a high-risk profile that requires enhanced due diligence.
                </p>
              </div>

              {/* AI Suggestions */}
              <div>
                <h4 className="font-semibold text-gray-900 dark:text-white mb-4">AI-Suggested Actions</h4>
                <div className="space-y-3">
                  <div className="flex gap-4 p-4 bg-white dark:bg-gray-950 rounded-xl border border-blue-200 dark:border-blue-900">
                    <div className="w-7 h-7 bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-400 rounded-full flex items-center justify-center flex-shrink-0 font-semibold text-sm">
                      1
                    </div>
                    <div>
                      <h5 className="font-semibold text-gray-900 dark:text-white mb-1">Request Additional Documentation</h5>
                      <p className="text-sm text-gray-600 dark:text-gray-400">Ask employer for contract/invoice justifying the $15K payment and confirm the business relationship with the contractor.</p>
                    </div>
                  </div>
                  <div className="flex gap-4 p-4 bg-white dark:bg-gray-950 rounded-xl border border-blue-200 dark:border-blue-900">
                    <div className="w-7 h-7 bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-400 rounded-full flex items-center justify-center flex-shrink-0 font-semibold text-sm">
                      2
                    </div>
                    <div>
                      <h5 className="font-semibold text-gray-900 dark:text-white mb-1">Temporarily Hold & Contact Employer</h5>
                      <p className="text-sm text-gray-600 dark:text-gray-400">Hold the transaction for 24-48 hours while conducting enhanced verification. This is standard practice for anomalous patterns.</p>
                    </div>
                  </div>
                  <div className="flex gap-4 p-4 bg-white dark:bg-gray-950 rounded-xl border border-emerald-200 dark:border-emerald-900">
                    <div className="w-7 h-7 bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-400 rounded-full flex items-center justify-center flex-shrink-0 font-semibold text-sm">
                      3
                    </div>
                    <div>
                      <h5 className="font-semibold text-gray-900 dark:text-white mb-1">Monitor & Escalate if Needed</h5>
                      <p className="text-sm text-gray-600 dark:text-gray-400">If employer provides satisfactory explanation, approve with enhanced monitoring. Escalate to senior compliance officer if documentation is insufficient.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Transaction Timeline */}
            <div className="bg-white dark:bg-gray-950 rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">Transaction Timeline</h3>
              <div className="space-y-6">
                <div className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-10 h-10 bg-red-100 dark:bg-red-950 rounded-full flex items-center justify-center">
                      <AlertTriangle className="w-5 h-5 text-red-600 dark:text-red-400" />
                    </div>
                    <div className="w-0.5 h-full bg-gray-200 dark:bg-gray-800 mt-2"></div>
                  </div>
                  <div className="pb-8 flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-semibold text-gray-900 dark:text-white">Transaction Flagged</h4>
                      <span className="px-2 py-0.5 bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-400 text-xs font-semibold rounded-full">High Risk</span>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">AI detected multiple risk indicators</p>
                    <p className="text-xs text-gray-500">Today at 2:34 PM</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-10 h-10 bg-blue-100 dark:bg-blue-950 rounded-full flex items-center justify-center">
                      <TrendingUp className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    </div>
                    <div className="w-0.5 h-full bg-gray-200 dark:bg-gray-800 mt-2"></div>
                  </div>
                  <div className="pb-8 flex-1">
                    <h4 className="font-semibold text-gray-900 dark:text-white mb-1">Transaction Initiated</h4>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Employer: TechCorp Inc</p>
                    <p className="text-xs text-gray-500">Today at 2:30 PM</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-10 h-10 bg-emerald-100 dark:bg-emerald-950 rounded-full flex items-center justify-center">
                      <CheckCircle className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                    </div>
                  </div>
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900 dark:text-white mb-1">Contractor KYC Approved</h4>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">All verification checks passed</p>
                    <p className="text-xs text-gray-500">3 days ago</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column */}
          <div className="space-y-6">
            {/* Transaction Summary */}
            <div className="bg-white dark:bg-gray-950 rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Transaction Summary</h3>
              <div className="space-y-4">
                <div>
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-1">Amount</div>
                  <div className="text-2xl font-bold text-gray-900 dark:text-white">$15,000.00</div>
                </div>
                <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">From</div>
                  <div className="font-semibold text-gray-900 dark:text-white mb-1">TechCorp Inc</div>
                  <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                    <MapPin className="w-4 h-4" />
                    San Francisco, CA
                  </div>
                </div>
                <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">To</div>
                  <div className="font-semibold text-gray-900 dark:text-white mb-1">Carlos Rodriguez</div>
                  <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                    <MapPin className="w-4 h-4" />
                    Buenos Aires, Argentina
                  </div>
                </div>
                <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">Reference ID</div>
                  <div className="flex items-center gap-2">
                    <code className="flex-1 px-3 py-2 bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white rounded-lg text-sm font-mono">
                      TXN-2024-0482
                    </code>
                    <button className="p-2 hover:bg-gray-100 dark:hover:bg-gray-900 rounded-lg transition-colors">
                      <Copy className="w-4 h-4 text-gray-600 dark:text-gray-400" />
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Documents */}
            <div className="bg-white dark:bg-gray-950 rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Related Documents</h3>
              <div className="space-y-2">
                {['Contractor ID (Front)', 'Proof of Address', 'Selfie Verification'].map((doc, i) => (
                  <button key={i} className="w-full flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors">
                    <FileText className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    <div className="flex-1 text-left">
                      <div className="text-sm font-medium text-gray-900 dark:text-white">{doc}</div>
                      <div className="text-xs text-gray-500">PDF Document</div>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Notes */}
            <div className="bg-white dark:bg-gray-950 rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Compliance Notes</h3>
              <textarea
                placeholder="Add internal notes about this review..."
                rows={4}
                className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-lg text-gray-900 dark:text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              />
              <button className="w-full mt-3 px-4 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors">
                Save Note
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
