-- ============================================
-- Migration: Create x402_endpoints Table
-- Purpose: Enable API providers to register endpoints that accept x402 payments
-- Spec: https://www.x402.org/x402-whitepaper.pdf
-- ============================================

-- Create x402_endpoints table
CREATE TABLE x402_endpoints (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  
  -- Endpoint Definition
  name TEXT NOT NULL,
  path TEXT NOT NULL,
  method TEXT NOT NULL CHECK (method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'ANY')),
  description TEXT,
  
  -- Pricing (Stablecoins only per x402 spec)
  base_price DECIMAL(10,4) NOT NULL CHECK (base_price > 0),
  currency TEXT NOT NULL DEFAULT 'USDC' CHECK (currency IN ('USDC', 'EURC')),
  volume_discounts JSONB DEFAULT NULL,
  -- volume_discounts structure: [{ "threshold": 1000, "priceMultiplier": 0.8 }]
  
  -- x402 Protocol Fields (per x402.org spec)
  payment_address TEXT, -- Wallet address or internal identifier
  asset_address TEXT,   -- ERC20 contract address (e.g., USDC on Base)
  network TEXT NOT NULL DEFAULT 'base-mainnet', -- base-mainnet, ethereum-mainnet, etc.
  
  -- Statistics (denormalized for performance)
  total_calls INTEGER NOT NULL DEFAULT 0 CHECK (total_calls >= 0),
  total_revenue DECIMAL(15,4) NOT NULL DEFAULT 0 CHECK (total_revenue >= 0),
  
  -- Status
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'disabled')),
  webhook_url TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Constraints
  UNIQUE(tenant_id, path, method)
);

-- Add comments
COMMENT ON TABLE x402_endpoints IS 'API endpoints that accept x402 payments (HTTP 402 Payment Required)';
COMMENT ON COLUMN x402_endpoints.base_price IS 'Base price per API call (up to 4 decimals for micropayments)';
COMMENT ON COLUMN x402_endpoints.currency IS 'Payment currency - stablecoins only (USDC, EURC) per x402 spec';
COMMENT ON COLUMN x402_endpoints.volume_discounts IS 'Optional volume pricing: [{ threshold, priceMultiplier }]';
COMMENT ON COLUMN x402_endpoints.payment_address IS 'Wallet address for receiving payments (internal or on-chain)';
COMMENT ON COLUMN x402_endpoints.asset_address IS 'ERC20 contract address for the payment token';
COMMENT ON COLUMN x402_endpoints.network IS 'Blockchain network for payments (base-mainnet, ethereum-mainnet, etc.)';
COMMENT ON COLUMN x402_endpoints.total_calls IS 'Total number of successful x402 payments to this endpoint';
COMMENT ON COLUMN x402_endpoints.total_revenue IS 'Total revenue generated by this endpoint';

-- Create indexes
CREATE INDEX idx_x402_endpoints_tenant ON x402_endpoints(tenant_id);
CREATE INDEX idx_x402_endpoints_account ON x402_endpoints(account_id);
CREATE INDEX idx_x402_endpoints_status ON x402_endpoints(status);
CREATE INDEX idx_x402_endpoints_created ON x402_endpoints(created_at DESC);
CREATE INDEX idx_x402_endpoints_path ON x402_endpoints(path);

-- Enable RLS
ALTER TABLE x402_endpoints ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Tenants can view their own x402 endpoints" ON x402_endpoints
  FOR SELECT
  USING (tenant_id = (SELECT public.get_user_tenant_id()));

CREATE POLICY "Tenants can create x402 endpoints" ON x402_endpoints
  FOR INSERT
  WITH CHECK (tenant_id = (SELECT public.get_user_tenant_id()));

CREATE POLICY "Tenants can update their own x402 endpoints" ON x402_endpoints
  FOR UPDATE
  USING (tenant_id = (SELECT public.get_user_tenant_id()));

CREATE POLICY "Tenants can delete their own x402 endpoints" ON x402_endpoints
  FOR DELETE
  USING (tenant_id = (SELECT public.get_user_tenant_id()));

-- Trigger for updated_at
CREATE TRIGGER update_x402_endpoints_updated_at
  BEFORE UPDATE ON x402_endpoints
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Grant permissions (if needed)
GRANT SELECT, INSERT, UPDATE, DELETE ON x402_endpoints TO authenticated;

-- Verification
DO $$
BEGIN
  RAISE NOTICE '✅ x402_endpoints table created successfully';
  RAISE NOTICE '✅ RLS policies enabled for tenant isolation';
  RAISE NOTICE '✅ Stablecoin-only currency constraint active';
  RAISE NOTICE '✅ x402 protocol compliance implemented';
END $$;

