import { Card } from '../ui/Card';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { 
  ArrowLeft, 
  AlertTriangle, 
  Sparkles, 
  CheckCircle2, 
  FileText, 
  XCircle,
  Clock,
  MapPin,
  CreditCard
} from 'lucide-react';

export function ComplianceFlagDetail() {
  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm">
          <ArrowLeft className="w-4 h-4" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-gray-900 dark:text-gray-100">Transaction #TXN-2024-0482</h1>
            <Badge variant="error">High Risk</Badge>
          </div>
          <p className="text-gray-600 dark:text-gray-400">Flagged 2 hours ago • Awaiting review</p>
        </div>
        <div className="flex gap-2">
          <Button variant="ghost" size="md">
            Request Documents
            <FileText className="w-4 h-4" />
          </Button>
          <Button variant="destructive" size="md">
            Block Transaction
            <XCircle className="w-4 h-4" />
          </Button>
          <Button variant="primary" size="md">
            Approve Transaction
            <CheckCircle2 className="w-4 h-4" />
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column - Transaction Details */}
        <div className="lg:col-span-2 space-y-6">
          {/* AI Explanation - The "Wow" Feature */}
          <Card className="border-2 border-primary-200 dark:border-primary-900 bg-gradient-to-br from-primary-50 to-white dark:from-primary-950 dark:to-gray-900">
            <div className="flex items-start gap-3 mb-4">
              <div className="p-2 bg-primary-600 rounded-lg">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="text-gray-900 dark:text-gray-100 mb-1">AI Compliance Analysis</h3>
                <p className="text-gray-600 dark:text-gray-400">Generated by PayOS Compliance Copilot</p>
              </div>
            </div>

            <div className="space-y-4">
              {/* Why Flagged */}
              <div>
                <h4 className="text-gray-900 dark:text-gray-100 mb-2 flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 text-error-600 dark:text-error-400" />
                  Why This Was Flagged
                </h4>
                <ul className="space-y-2 ml-6">
                  <li className="text-gray-700 dark:text-gray-300 list-disc">
                    <strong>Unusual transaction pattern:</strong> This contractor typically receives $2,500-$3,000 monthly. This $15,000 payment is 5x the normal amount.
                  </li>
                  <li className="text-gray-700 dark:text-gray-300 list-disc">
                    <strong>Geographic risk:</strong> First payment to a contractor in a high-risk jurisdiction (based on FATF guidance).
                  </li>
                  <li className="text-gray-700 dark:text-gray-300 list-disc">
                    <strong>Velocity alert:</strong> Third transaction from this employer in the past 24 hours, totaling $42,000.
                  </li>
                  <li className="text-gray-700 dark:text-gray-300 list-disc">
                    <strong>KYC timing:</strong> Contractor completed KYC only 3 days ago. Typically we see a longer lead time before large payments.
                  </li>
                </ul>
              </div>

              {/* Risk Assessment */}
              <div className="pt-4 border-t border-primary-200 dark:border-primary-900">
                <h4 className="text-gray-900 dark:text-gray-100 mb-2">Risk Assessment</h4>
                <div className="flex items-start gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <div className="flex-1 h-2 bg-gray-200 dark:bg-gray-800 rounded-full overflow-hidden">
                        <div className="h-full bg-error-600 rounded-full" style={{ width: '85%' }}></div>
                      </div>
                      <span className="text-error-600 dark:text-error-400">85% Risk Score</span>
                    </div>
                    <p className="text-gray-700 dark:text-gray-300">
                      While the individual factors are explainable, the combination of velocity, amount anomaly, and timing creates a high-risk profile that requires enhanced due diligence.
                    </p>
                  </div>
                </div>
              </div>

              {/* Suggested Actions */}
              <div className="pt-4 border-t border-primary-200 dark:border-primary-900">
                <h4 className="text-gray-900 dark:text-gray-100 mb-3">AI-Suggested Actions</h4>
                <div className="space-y-2">
                  <div className="flex items-start gap-3 p-3 bg-white dark:bg-gray-900 rounded-lg border border-primary-200 dark:border-primary-800">
                    <div className="w-6 h-6 bg-warning-100 dark:bg-warning-900 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-warning-700 dark:text-warning-300">1</span>
                    </div>
                    <div className="flex-1">
                      <div className="text-gray-900 dark:text-gray-100 mb-1">Request Additional Documentation</div>
                      <p className="text-gray-600 dark:text-gray-400">Ask employer for contract/invoice justifying the $15K payment and confirm the business relationship with the contractor.</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3 p-3 bg-white dark:bg-gray-900 rounded-lg border border-primary-200 dark:border-primary-800">
                    <div className="w-6 h-6 bg-warning-100 dark:bg-warning-900 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-warning-700 dark:text-warning-300">2</span>
                    </div>
                    <div className="flex-1">
                      <div className="text-gray-900 dark:text-gray-100 mb-1">Temporarily Hold & Contact Employer</div>
                      <p className="text-gray-600 dark:text-gray-400">Hold the transaction for 24-48 hours while conducting enhanced verification. This is standard practice for anomalous patterns.</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3 p-3 bg-white dark:bg-gray-900 rounded-lg border border-primary-200 dark:border-primary-800">
                    <div className="w-6 h-6 bg-success-100 dark:bg-success-900 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-success-700 dark:text-success-300">3</span>
                    </div>
                    <div className="flex-1">
                      <div className="text-gray-900 dark:text-gray-100 mb-1">Monitor & Escalate if Needed</div>
                      <p className="text-gray-600 dark:text-gray-400">If employer provides satisfactory explanation, approve with enhanced monitoring. Escalate to senior compliance officer if documentation is insufficient.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Card>

          {/* Transaction Timeline */}
          <Card>
            <h3 className="text-gray-900 dark:text-gray-100 mb-4">Transaction Timeline</h3>
            <div className="space-y-4">
              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-3 h-3 bg-error-600 dark:bg-error-400 rounded-full"></div>
                  <div className="w-0.5 flex-1 bg-gray-200 dark:bg-gray-800 mt-2"></div>
                </div>
                <div className="pb-6">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-gray-900 dark:text-gray-100">Transaction Flagged</span>
                    <Badge variant="error">High Risk</Badge>
                  </div>
                  <p className="text-gray-600 dark:text-gray-400 mb-1">AI detected multiple risk indicators</p>
                  <span className="text-gray-500 dark:text-gray-500">Today at 2:34 PM</span>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-3 h-3 bg-primary-600 dark:bg-primary-400 rounded-full"></div>
                  <div className="w-0.5 flex-1 bg-gray-200 dark:bg-gray-800 mt-2"></div>
                </div>
                <div className="pb-6">
                  <span className="text-gray-900 dark:text-gray-100 mb-1 block">Transaction Initiated</span>
                  <p className="text-gray-600 dark:text-gray-400 mb-1">Employer: TechCorp Inc</p>
                  <span className="text-gray-500 dark:text-gray-500">Today at 2:30 PM</span>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-3 h-3 bg-success-600 dark:bg-success-400 rounded-full"></div>
                </div>
                <div>
                  <span className="text-gray-900 dark:text-gray-100 mb-1 block">Contractor KYC Approved</span>
                  <p className="text-gray-600 dark:text-gray-400 mb-1">All verification checks passed</p>
                  <span className="text-gray-500 dark:text-gray-500">3 days ago</span>
                </div>
              </div>
            </div>
          </Card>
        </div>

        {/* Right Column - Summary & Documents */}
        <div className="space-y-6">
          {/* Transaction Summary */}
          <Card>
            <h3 className="text-gray-900 dark:text-gray-100 mb-4">Transaction Summary</h3>
            <div className="space-y-4">
              <div>
                <span className="text-gray-600 dark:text-gray-400 block mb-1">Amount</span>
                <span className="text-gray-900 dark:text-gray-100">$15,000.00 USD</span>
              </div>
              <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                <span className="text-gray-600 dark:text-gray-400 block mb-1">From</span>
                <div className="text-gray-900 dark:text-gray-100 mb-1">TechCorp Inc</div>
                <div className="flex items-center gap-2 text-gray-600 dark:text-gray-400">
                  <MapPin className="w-4 h-4" />
                  San Francisco, CA
                </div>
              </div>
              <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                <span className="text-gray-600 dark:text-gray-400 block mb-1">To</span>
                <div className="text-gray-900 dark:text-gray-100 mb-1">Carlos Rodriguez</div>
                <div className="flex items-center gap-2 text-gray-600 dark:text-gray-400">
                  <MapPin className="w-4 h-4" />
                  Buenos Aires, Argentina
                </div>
              </div>
              <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                <span className="text-gray-600 dark:text-gray-400 block mb-1">Type</span>
                <div className="flex items-center gap-2">
                  <CreditCard className="w-4 h-4 text-gray-600 dark:text-gray-400" />
                  <span className="text-gray-900 dark:text-gray-100">Contractor Payout</span>
                </div>
              </div>
              <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
                <span className="text-gray-600 dark:text-gray-400 block mb-1">Reference ID</span>
                <code className="text-gray-900 dark:text-gray-100 bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">TXN-2024-0482</code>
              </div>
            </div>
          </Card>

          {/* Related Documents */}
          <Card>
            <h3 className="text-gray-900 dark:text-gray-100 mb-4">Related Documents</h3>
            <div className="space-y-2">
              <button className="w-full flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors">
                <FileText className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                <div className="flex-1 text-left">
                  <div className="text-gray-900 dark:text-gray-100">Contractor ID (Front)</div>
                  <div className="text-gray-500 dark:text-gray-500">passport_front.pdf</div>
                </div>
              </button>
              <button className="w-full flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors">
                <FileText className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                <div className="flex-1 text-left">
                  <div className="text-gray-900 dark:text-gray-100">Proof of Address</div>
                  <div className="text-gray-500 dark:text-gray-500">utility_bill.pdf</div>
                </div>
              </button>
              <button className="w-full flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors">
                <FileText className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                <div className="flex-1 text-left">
                  <div className="text-gray-900 dark:text-gray-100">Selfie Verification</div>
                  <div className="text-gray-500 dark:text-gray-500">selfie_check.jpg</div>
                </div>
              </button>
            </div>
          </Card>

          {/* Compliance Notes */}
          <Card>
            <h3 className="text-gray-900 dark:text-gray-100 mb-4">Compliance Notes</h3>
            <textarea
              placeholder="Add internal notes about this review..."
              className="w-full h-24 px-3 py-2 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
            <Button variant="secondary" size="sm" className="mt-2 w-full">
              Save Note
            </Button>
          </Card>
        </div>
      </div>
    </div>
  );
}
